//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tienda
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estudio
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public Nullable<int> fundacion { get; set; }
        public string pais { get; set; }
        public string descripcion { get; set; }
    }
}
