//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ud3Hoja2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        public int facturaId { get; set; }
        public int clienteId { get; set; }
        public int numero { get; set; }
        public System.DateTime fecha { get; set; }
        public double importeBase { get; set; }
        public int iva { get; set; }
        public double importeTotal { get; set; }
        public bool pagada { get; set; }
    }
}
