//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ud3Hoja2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public int productoId { get; set; }
        public string fabricante { get; set; }
        public double precio { get; set; }
        public int ancho { get; set; }
        public int alto { get; set; }
        public int radial { get; set; }
    }
}
