//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaVideojuegos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estudio
    {
        public string nombre { get; set; }
        public Nullable<int> inicio_actividad { get; set; }
        public string sede { get; set; }
    }
}
