//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaVideojuegos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Videojuego
    {
        public string titulo { get; set; }
        public string estudio { get; set; }
        public Nullable<System.DateTime> fecha_lanzamiento { get; set; }
        public Nullable<double> precio { get; set; }
    }
}
