//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ud2Hoja17
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gasto
    {
        public long GastoId { get; set; }
        public decimal Importe { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public long PersonaId { get; set; }
    }
}
